# Generated by Django 5.1.5 on 2025-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('diasReport', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='json',
            new_name='dias',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='month',
            new_name='mes',
        ),
        migrations.AddField(
            model_name='calendario',
            name='tramites',
            field=models.ManyToManyField(to='clients.tramite'),
        ),
    ]
