# Generated by Django 5.1.5 on 2025-01-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_tramite_rename_json_calendario_dias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='tramites',
        ),
        migrations.AddField(
            model_name='calendario',
            name='tramites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.tramite'),
            preserve_default=False,
        ),
    ]
